<?php

/**
 * @file
 * Module file for esdportal_scoresbybocode.
 *
 * Provide a page listing a certain school's raw test scores for review by a
 * school administrator.
 *
 */

/**
 * Implements hook_permission().
 */
function esdportal_scoresbybcode_permission() {
  return array(
    'access school scores' => array(
      'title' => t('Access school score pages'),
      'description' => t('Allow users to view school scores by bcode'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function esdportal_scoresbybcode_menu() {
  $items['schoolscores/%'] = array(
    'page callback' => 'esdportal_scoresbybcode_page',
    'page arguments' => array(1),
    'access arguments' => array('access school scores'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function esdportal_scoresbybcode_page($bcode) {
  // Validate bcode
  $bcode = intval($bcode);
  if ($bcode < 1) {
    return t('Please provide a numeric bcode.');
  }

  // Get school name
  $schoolname = db_query("SELECT ttd.name FROM {field_data_field_bcode} AS fdfb INNER JOIN {taxonomy_term_data} AS ttd ON fdfb.entity_id=ttd.tid WHERE fdfb.field_bcode_value=:bcode AND fdfb.entity_type='taxonomy_term'", array(':bcode' => $bcode))->fetchField();
  if (strlen($schoolname) < 2) {
    return t('Please provide a bcode for an ESD school.');
  }

  // Build groups of fields
  $fieldgroups = array(
    'Academic Status' => array(
      'description' => 'This would appear below the title, maybe',
      'fields' => array(
        'CSV High Expectations' => array(
          'description' => 'Something descriptive',
          'table' => 'esd_k8_2013',
          'column' => 'CSV_HEL_RAW',
          'value' => NULL, // set to non-null if db has value
          'denominator' => 1,
          'bcode_col' => 'buildingcode',
        ),
        '4 Year Graduation Rate' => array(
          'description' => 'Percentage of students who complete school in four years',
          'table' => 'esd_hs_2013',
          'column' => 'GRADRATE_RAW',
          'value' => NULL,
          'denominator' => 100,
          'bcode_col' => 'buildingcode',
        ),
      ),
    ),
  );

  $tables = '';
  // Build tables
  foreach ($fieldgroups as $groupname => &$data) {
    $header = array($groupname, t('Description'), t('Points possible'), t('Grade'));
    foreach ($data['fields'] as $field_name => $field_data) {
      $query = db_query("SELECT " . $field_data['column'] . " FROM {" . $field_data['table'] . "} WHERE " . $field_data['bcode_col'] . " = :bcode", array(':bcode' => $bcode));
      $value = $query->fetchField();
      $rows[] = array(
        $field_name,
        $field_data['description'],
        $field_data['denominator'],
        $value,
      );
    }

    $tables .= theme('table', array('header' => $header, 'rows' => $rows));
  }

  $render_array['esdportal_scoresbybcode_page'] = array(
    '#type' => 'markup',
    '#markup' => $tables,
    '#title' => t('Grade Report for @bcode', array('@bcode' => $bcode)),
  );

  return $render_array;
}

